[package]
name = "dxc-icons"
version = "0.1.0"
edition = "2021"
exclude = ["assets/**", "preview/**"]

[dependencies]
dioxus = { version = "0.6.3", features = ["fullstack"] }

[build-dependencies]
regex = "1.11.1"
