[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index/"
# replace-with = "aliyun"

[registries]
aliyun = { index = "https://mirrors.aliyun.com/crates.io-index/" }
crates-io = { index = "https://github.com/rust-lang/crates.io-index" }
